### PR TITLE
Docker: fix pull missing images with `--docker-auto-pull` (fixes #4598)

### LINKED ISSUE #4598: Pull specific images using --docker-auto-pull option
### Expected

Pull a suitable image automatically.

### Actual

```
$ stack --docker-auto-pull install
Error: No such object: fpco/stack-build:lts-13.8
Received ExitFailure 1 when running
Raw command: /snap/bin/docker inspect fpco/stack-build:lts-13.8
Standard output:

[]
```

### Stack version

```
$ stack --version
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

### PR DESCRIPTION
**Pull request by borsboom**
* [X] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [X] ~~The documentation has been updated, if necessary.~~ (N/A)

### CODE REVIEW

File: src/Stack/Docker.hs [hunk 1]
```diff
@@ -639,7 +639,8 @@ inspects :: (HasProcessContext env, HasLogFunc env)
          => [String] -> RIO env (Map String Inspect)
 inspects [] = return Map.empty
 inspects images =
-  do maybeInspectOut <- try (readDockerProcess ("inspect" : images))
+  do maybeInspectOut <-
+       try (BL.toStrict . fst <$> proc "docker" ("inspect" : images) readProcess_)
```
Comment (dbaynard) [inline src/Stack/Docker.hs]: Is it worth fixing `readDockerProcess` rather than overriding it? I notice that there's a FIXME in the below code.

https://github.com/commercialhaskell/stack/blob/b01c526c733d30ab2df8fa296e0e02f6314c15be/src/Stack/Docker.hs#L844-L850

Comment (borsboom) [reply src/Stack/Docker.hs]: That was what I tried first, but the current `readDockerProcess` behaviour of passing stderr straight through is desirable for some docker commands such as `docker pull` (so you can see the fancy pull progress that Docker outputs).

Comment (snoyberg) [reply src/Stack/Docker.hs]: If that's the case, I think the FIXME can be removed (and thanks for noticing that David).
