### PR TITLE
Show warning about `local-programs-path` with spaces on windows when running scripts

### LINKED ISSUE #5001: Show warning about path with spaces in windows when running scripts
### Steps to reproduce
1. Set a path with spaces in the `local-program-path` of `%STACK_ROOT%\config.yaml`
```
local-programs-path: D:\bin\s t a c k
```
2. Create simple file script `example.hs`:
```haskell
 #!/usr/bin/env stack
{- stack
  runghc
  --resolver=lts-14.1
-}
main = putStrLn "Hello"
```
2. Run command `stack example.hs`.

### Expected

Show the same warning as you run `stack <command>`:

```console
PS D:\dev\ws\haskell\stack-test> stack build
Stack's 'programs' path contains a space character and has no alternative short ('8 dot 3') name. This will cause problems with packages that use the GNU project's 'configure' shell script. Use the 'local-programs-path' configuation option to specify an alternative path. The current 'shortest' path is: D:\bin\s t a c k\
```

### Actual

It shows nothing about the possible issues caused by that configuration.

[The original issue was in haskell-ide-engine](https://github.com/haskell/haskell-ide-engine/issues/1356): a user with spaces in `%USER_PROFILE%` (very common in windows versions below 10 or win 10 migrated from older one) and the default `local-programs-path`  got an error running the script to install hie executable:
```
install.hs: C:\Users\Arthur: createProcess: does not exist (No such file or directory)
```
Setting `local-programs-path` without spaces fixed the error.

(As a side note i found the warning message a little bit weird: `'8 dot 3'`? `The current 'shortest' path is: D:\bin\s t a c k\`? and has a typo: `configuation`)

### Stack version

```
$ stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

### PR DESCRIPTION
**Pull request by jneira**
Please include the following checklist in your PR:

* [X] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [X] The documentation has been updated, if necessary.

It seems that warn messages are [not shown when running a script](https://github.com/commercialhaskell/stack/issues/3007) so the more straigthforward way is change the log level of the relevant message. Not sure it it could have a unwanted consequence.
It fixes #5001.

I've tested the change manually running a script to check the message is actually shown.

### CODE REVIEW

File: src/Stack/Config.hs [hunk 1]
```diff
@@ -281,7 +281,7 @@ configFromConfigMonoid
        shortLocalProgramsFilePath <-
          liftIO $ getShortPathName localProgramsFilePath
        when (' ' `elem` shortLocalProgramsFilePath) $ do
-         logWarn $ "Stack's 'programs' path contains a space character and " <>
+         logError $ "Stack's 'programs' path contains a space character and " <>
            "has no alternative short ('8 dot 3') name. This will cause " <>
            "problems with packages that use the GNU project's 'configure' " <>
            "shell script. Use the 'local-programs-path' configuation option " <>
```
Comment (dbaynard) [inline src/Stack/Config.hs]:
```suggestion
           "shell script. Use the 'local-programs-path' configuration option " <>
```

Might as well fix the typo!

**Comment by jneira** [comment]
@dbaynard not sure about the best way to inform the user, but it seems that show the original value of `local-programs-path` could help it to identify and change it.
