### PR TITLE
Change parsers to use `flag'` instead of `switch`

### LINKED ISSUE #3959: It should not matter if flags given before command or after
This happened in a wrapper script, when I'm setting default flags to pass to stack; e.g.

```
#!/bin/bash
STACK_ARGS=(
    --test --no-run-tests
    --bench --no-run-benchmarks
)
exec stack "${STACK_ARGS[@]}" "$@"
```

### Steps to reproduce

1. `stack --test --no-run-tests build`
2. `stack build --test --no-run-tests`

### Expected

Either both should build tests and not run them or neither should work (since `stack` doesn't take those flags on its own)

### Actual

The first built and ran tests. The second built but didn't run tests.

In other words, `stack --test build` and `stack --test --no-run-tests build` do the same thing.

### Stack version

```
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```

### Method of installation

From `https://github.com/commercialhaskell/stack/releases/download`

### PR DESCRIPTION
**Pull request by markus1189**
This fixes #3959.

The problem is that the [switch](https://hackage.haskell.org/package/optparse-applicative/docs/Options-Applicative-Builder.html#v:switch) function returns a `Just False` which gets wrapped into `First`.

This means that the value is *always* set to either `True` or `False`
and the `First` monoid means that during options parsing the order of
the flags suddenly matters as described in #3959, because `First (Just
False)` is chosen when `mappend`ing with `First (Just True)`.

The fix is to use the [flag](https://hackage.haskell.org/package/optparse-applicative-0.14.2.0/docs/Options-Applicative-Builder.html#v:flag-39-) function that does not set a default value, so we get a `First Nothing` instead.

Note: Documentation fixes for https://docs.haskellstack.org/en/stable/ should target the "stable" branch, not master.

Please include the following checklist in your PR:

* [x] Any changes that could be relevant to users have been recorded in the ChangeLog.md
  there should be no user relevant changes
* [x] The documentation has been updated, if necessary.
  no relevant changes

Please also shortly describe how you tested your change. Bonus points for added tests!
There is a new integration test in the `3959-order-of-flags` folder that makes sure that the order does not matter.

### CODE REVIEW

File: test/integration/tests/3959-order-of-flags/files/test/Spec.hs [hunk 1]
```diff
@@ -0,0 +1,2 @@
+main :: IO ()
+main = putStrLn "Test suite not yet implemented"
```
Comment (snoyberg) [inline test/integration/tests/3959-order-of-flags/files/test/Spec.hs]: Can you make this a failing line so we're sure that the test suite isn't run?

File: test/integration/tests/3959-order-of-flags/files/stack.yaml [hunk 2]
```diff
@@ -0,0 +1,65 @@
+# This file was automatically generated by 'stack init'
```
Comment (snoyberg) [inline test/integration/tests/3959-order-of-flags/files/stack.yaml]: Can you replace this with `resolver: lts-11.6`

File: test/integration/tests/3959-order-of-flags/files/src/Lib.hs [hunk 3]
```diff
@@ -0,0 +1,6 @@
+module Lib
```
Comment (snoyberg) [inline test/integration/tests/3959-order-of-flags/files/src/Lib.hs]: It should work to drop this module.

File: test/integration/tests/3959-order-of-flags/files/bug3959.cabal [hunk 4]
```diff
@@ -0,0 +1,61 @@
+-- This file has been generated from package.yaml by hpack version 0.28.2.
```
Comment (snoyberg) [inline test/integration/tests/3959-order-of-flags/files/bug3959.cabal]: I'd recommend replacing this .cabal file with a package.yaml file instead.

File: test/integration/tests/3959-order-of-flags/files/app/Main.hs [hunk 5]
```diff
@@ -0,0 +1,6 @@
+module Main where
```
Comment (snoyberg) [inline test/integration/tests/3959-order-of-flags/files/app/Main.hs]: This can be dropped too.

File: test/integration/tests/3959-order-of-flags/files/Setup.hs [hunk 6]
```diff
@@ -0,0 +1,2 @@
+import Distribution.Simple
```
Comment (snoyberg) [inline test/integration/tests/3959-order-of-flags/files/Setup.hs]: This can be dropped too.

File: src/Stack/Options/BenchParser.hs [hunk 7]
```diff
@@ -19,7 +19,7 @@ benchOptsParser hide0 = BenchmarkOptsMonoid
                                  help ("Forward BENCH_ARGS to the benchmark suite. " <>
                                        "Supports templates from `cabal bench`") <>
                                  hide))
-        <*> optionalFirst (switch (long "no-run-benchmarks" <>
+        <*> optionalFirst (flag' True (long "no-run-benchmarks" <>
```
Comment (snoyberg) [inline src/Stack/Options/BenchParser.hs]: Can you add a comment to the changelog about the bugfix?

**Comment by mihaimaruseac** [comment]
Looks good on a quick glance. Minor nit, though: can you remove the autogenerated comments in the files for the integration tests?

File: src/Stack/Options/BenchParser.hs (hunk 7 above)
Comment (markus1189) [reply src/Stack/Options/BenchParser.hs]: done

**Comment by snoyberg** [comment]
Thanks!
