### PR TITLE
Fix #4726: On Windows, inform or warn about 'programs' path with space

### LINKED ISSUE #4726: Windows: Need local-programs-path with no space in path, if no short (8 dot 3) name exists for default
I can't build the current stack master (last commit is  abf4ca08706e02256a500e507ff7ec47c21e55c8, a clean clone from GitHub) with stack (version is: Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1, a clean download of the binary) on Windows 10. It always fails at the `process-1.6.3.0` step. For example:

~~~~
C:\Users\Mike Pilgrem\Documents\Code\Haskell\stack>stack install
WARNING: Ignoring out of range dependency (trusting snapshot over Hackage revisions): Cabal-2.4.0.1. lens requires: >=1.10 && <2.3
process-1.6.3.0: configure
Progress 1/54

--  While building package process-1.6.3.0 using:
      C:\Users\Mike Pilgrem\AppData\Local\Temp\stack28980\process-1.6.3.0\.stack-work\dist\5c8418a7\setup\setup --builddir=.stack-work\dist\5c8418a7 configure "--with-ghc=C:\\Users\\Mike Pilgrem\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.2.2\\bin\\ghc.EXE" "--with-ghc-pkg=C:\\Users\\Mike Pilgrem\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.2.2\\bin\\ghc-pkg.EXE" --user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\dbfc50c3\pkgdb --libdir=C:\sr\snapshots\dbfc50c3\lib --bindir=C:\sr\snapshots\dbfc50c3\bin --datadir=C:\sr\snapshots\dbfc50c3\share --libexecdir=C:\sr\snapshots\dbfc50c3\libexec --sysconfdir=C:\sr\snapshots\dbfc50c3\etc --docdir=C:\sr\snapshots\dbfc50c3\doc\process-1.6.3.0 --htmldir=C:\sr\snapshots\dbfc50c3\doc\process-1.6.3.0 --haddockdir=C:\sr\snapshots\dbfc50c3\doc\process-1.6.3.0 --dependency=Win32=Win32-2.5.4.1 --dependency=base=base-4.10.1.0 --dependency=deepseq=deepseq-1.4.3.0 --dependency=directory=directory-1.3.0.2 --dependency=filepath=filepath-1.4.1.2 "--extra-include-dirs=C:\\Users\\Mike Pilgrem\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20180531\\mingw64\\include" "--extra-lib-dirs=C:\\Users\\Mike Pilgrem\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20180531\\mingw64\\bin" "--extra-lib-dirs=C:\\Users\\Mike Pilgrem\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20180531\\mingw64\\lib"
    Process exited with code: ExitFailure 77
    Logs have been written to: C:\Users\Mike Pilgrem\Documents\Code\Haskell\stack\.stack-work\logs\process-1.6.3.0.log

    [1 of 2] Compiling Main             ( C:\Users\Mike Pilgrem\AppData\Local\Temp\stack28980\process-1.6.3.0\Setup.hs, C:\Users\Mike Pilgrem\AppData\Local\Temp\stack28980\process-1.6.3.0\.stack-work\dist\5c8418a7\setup\Main.o )
    [2 of 2] Compiling StackSetupShim   ( C:\sr\setup-exe-src\setup-shim-Z6RU0evB.hs, C:\Users\Mike Pilgrem\AppData\Local\Temp\stack28980\process-1.6.3.0\.stack-work\dist\5c8418a7\setup\StackSetupShim.o )
    Linking C:\Users\Mike Pilgrem\AppData\Local\Temp\stack28980\process-1.6.3.0\.stack-work\dist\5c8418a7\setup\setup.exe ...
    Configuring process-1.6.3.0...
    configure: WARNING: unrecognized options: --with-compiler
    configure: loading site script /usr/local/etc/config.site
    checking for gcc... C:\Users\Mike Pilgrem\AppData\Local\Programs\stack\X86_64~1\GHC-82~1.2\mingw\bin\gcc.exe
    checking whether the C compiler works... no
    configure: error: in `/c/Users/Mike Pilgrem/AppData/Local/Temp/stack28980/process-1.6.3.0':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
~~~~

Given the reference in the error message above to `gcc`, in case it is relevant:
~~~~
C:\Users\Mike Pilgrem\Documents\Code\Haskell\stack>stack exec where -- gcc
C:\Users\Mike Pilgrem\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\mingw\bin\gcc.exe
C:\Program Files\Haskell Platform\8.6.3\mingw\bin\gcc.exe

C:\Users\Mike Pilgrem\Documents\Code\Haskell\stack>stack exec gcc -- --version
realgcc.exe (Rev2, Built by MSYS2 project) 6.2.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
~~~~

### PR DESCRIPTION
**Pull request by mpilgrem**
In module `Stack.Config`, function `configFromConfigMonoid`, a stack user is informed if the stack 'programs' path contains a space character. If the path also does not have an alternative short ('8 dot 3') name, the user is further warned of the implications for packages that make use of the GNU project's `configure` shell script.

New modules `System.Info` are added to `src/windows` and `src/unix` to re-export `getShortPathName` from the `System.Win32.Info` module of the `Win32` package in the case of Windows and do nothing in the case of Unix-like operating systems. This avoids the need for C preprocessor (CPP) directives in `Stack.Config`.

`ChangeLog.md` is updated, accordingly.

Tested on Windows 10 with 'programs' paths that do and do not contain space characters and, in the latter case, with paths that do and do not have '8 dot 3' names. Tested with paths that do not yet exist when stack is first run.

Note: Documentation fixes for https://docs.haskellstack.org/en/stable/ should target the "stable" branch, not master.

Please include the following checklist in your PR:

* [x] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [x] The documentation has been updated, if necessary. N/A - documentation was the subject of #4798.

Please also shortly describe how you tested your change. Bonus points for added tests! See above.

### CODE REVIEW

File: src/Stack/Config.hs [hunk 1]
```diff
@@ -270,6 +271,24 @@ configFromConfigMonoid
      configLocalProgramsBase <- case getFirst configMonoidLocalProgramsBase of
        Nothing -> getDefaultLocalProgramsBase configStackRoot configPlatform origEnv
        Just path -> return path
+     let localProgramsFilePath = toFilePath configLocalProgramsBase
+     when (osIsWindows && ' ' `elem` localProgramsFilePath) $ do
+       logInfo $ "Stack's 'programs' path contains a space character. " <>
```
Comment (snoyberg) [inline src/Stack/Config.hs]: It seems a bit excessive to always print this message, given that on many systems this setup will work just fine. The warning below seems like it will address the actual problem: warning the user when there will almost certainly be some problem.

**Comment by snoyberg** [comment]
Note that the CI build failed:

```
stack> /home/vsts/work/1/s/src/unix/System/Info.hs:9:33: error:
stack>     Not in scope: type constructor or class ‘IO’
stack>   |
stack> 9 | getShortPathName :: FilePath -> IO FilePath
```

File: src/Stack/Config.hs (hunk 1 above)
Comment (mpilgrem) [reply src/Stack/Config.hs]: I have revised the pull request to only include the warning (and to fix the CI failures).
