### PR TITLE
Nix: select the right GHC version in more cases.

### LINKED ISSUE #1641: stack --nix --resolver doesn't work as expected
Passing a concrete resolver on the command-line correctly overrides the resolver found in the stack.yaml, but passing an abstract resolver does not.

Example:

```
$ stack new --bare --resolver lts-4.1 foo
$ stack --nix --resolver lts-2.22 build
...
```

Compared to:

```
$ stack --nix --resolver lts-2 build
Selected resolver: lts-2.22
Compiler version mismatched, found ghc-7.10.2 (x86_64), but expected minor version match with ghc-7.8.4 (x86_64) (based on resolver setting in /tmp/foo/stack.yaml).
```

### PR DESCRIPTION
**Pull request by mboes**
Stack now selects the correct GHC version in the following cases:

* an abstract resolver was given,
* a concrete resolver was given,
* a compiler version was given.

Previously, we could only deal with concrete resolvers correctly. So
e.g.

```
$ stack --resolver lts-2 build
```

should now use GHC-7.8.4 from the nixpkgs repo. I think exactly the same
approach should be workable for Docker too, but how exactly the use case
should work there is less clear to me.

Fixes #1641.

### CODE REVIEW

File: src/Stack/Types/Config.hs-boot [hunk 1]
```diff
@@ -0,0 +1,5 @@
+module Stack.Types.Config where
```
Comment (mboes) [inline src/Stack/Types/Config.hs-boot]: Note: An alternative to using an .hs-boot file is to parameter `NixOpts` over the resolver type. I found the .hs-boot file to be less verbose in the end.

**Comment by mboes** [comment]
cc @YPares

**Comment by borsboom** [comment]
LGTM, and I'll try to apply this approach to Docker as well.
