### PR TITLE
No FK checks during migrations and better error if migration fails

### LINKED ISSUE #4519: almost all stack actions result in SQLite error ...
`stack build`, `stack ghci`, `stack upgrade ...` all fail ... it's a reasonably unfortunate situation.

i'm running the latest from master:

```
07:02 PM noon ∈ ~ ♫ stack --version
Version 1.10.0, Git revision ac20e0da239d2e3f6a7cb4bb67ea33b2a7c95849 x86_64 hpack-0.31.1
```

most unfortunately, it also affects `stack upgrade`:

```
07:02 PM noon ∈ ~ ♫ stack upgrade  
SQLite3 returned ErrorConstraint while attempting to perform step: FOREIGN KEY constraint failed
```

and when running again:

```
07:02 PM noon ∈ ~ ♫ stack upgrade
SQLite3 returned ErrorBusy while attempting to perform step: database is locked
```

( as an aside, i feel like the master branch is much more unstable in the last 6 months or so; i used to upgrade all the time; now, whenever i do i hit some weird bug. maybe the "stack upgrade --git" option could hit a more stable branch, if master isn't stable anymore? )

### PR DESCRIPTION
**Pull request by qrilka**
Note: Documentation fixes for https://docs.haskellstack.org/en/stable/ should target the "stable" branch, not master.

Please include the following checklist in your PR:

* [ ] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [ ] The documentation has been updated, if necessary.

Tested it manually with a DB created with Stack sources before #4439 was merged

Fixes #4519 

@snoyberg is it OK to reference `$STACK_ROOT` in Pantry error messages? It doesn't look clean to me but I'm not sure how to deal with it better in this case

### CODE REVIEW

File: subs/pantry/src/Pantry/Storage.hs [hunk 1]
```diff
@@ -215,15 +215,17 @@ initStorage
...
-    inner (P.Storage pool)
+    migrates <- wrapMigrationFailure $ runSqlPool (runMigrationSilent migrateAll) pool
+    forM_ migrates $ \mig -> logDebug $ "Migration executed: " <> display mig
+  bracket
+    (createSqlitePoolFromInfo (sqinfo True) 1)
+    (liftIO . destroyAllResources) $ \pool -> inner (P.Storage pool)
   where
-    sqinfo = set extraPragmas ["PRAGMA busy_timeout=2000;"]
-           $ set fkEnabled True
+    wrapMigrationFailure = handle (throwIO . MigrationFailure)
```
Comment (snoyberg) [inline subs/pantry/src/Pantry/Storage.hs]: How about including the `FilePath` above in the `MigrationFailure` data constructor, and replacing the `$STACK_ROOT` bit with the actual file path they would need to delete?

Comment (qrilka) [reply subs/pantry/src/Pantry/Storage.hs]: Fixed
