### PR TITLE
Correct recommendation for older Stack (fixes #4931)

### LINKED ISSUE #4931: Improve error message concerning "Stack no longer supported Cabal versions below..."
My Travis CI build for BNFC to test ghc-7.8 compilation suddenly fails with:
```
Stack no longer supported Cabal versions below 1.19.2,
but version 1.18.1.5was found.
This invocation will most likely fail.
To fix this, either use a newer version of Stack or a newer resolver
Acceptable resolvers: lts-3.0/nightly-2015-05-05 or later
```
(Btw: note the missing space in `1.18.1.5was`. And the dubious grammar `Stack no longer supported`; why past tense and not present tense `supports`?!)
The build log is here:
https://travis-ci.org/BNFC/bnfc/jobs/552087712
Last successful build was on May 24th:
https://travis-ci.org/BNFC/bnfc/jobs/536791354
The stack config file at https://github.com/BNFC/bnfc/blob/master/stack-7.8.4.yaml just says:
```
resolver: lts-2.22
packages:
- source
- testing
```
Here is my travis configuration file:
https://github.com/BNFC/bnfc/blob/master/.travis.yml

### PR DESCRIPTION
**Pull request by snoyberg**

### CODE REVIEW

File: src/Stack/Setup.hs [hunk 1]
```diff
@@ -507,7 +507,7 @@ warnUnsupportedCompilerCabal cp didWarn = do
         logWarn $ "Stack no longer supported Cabal versions below 1.19.2,"
```
Comment (andreasabel) [inline src/Stack/Setup.hs]: supports

File: src/Stack/Setup.hs [hunk 2]
```diff
@@ -507,7 +507,7 @@ warnUnsupportedCompilerCabal cp didWarn = do
...
         logWarn $ "but version " <> fromString (versionString cabalVersion) <> "was found."
```
Comment (andreasabel) [inline src/Stack/Setup.hs]: space, like " was found"
