### PR TITLE
Cache exposed package modules in Pantry DB

### LINKED ISSUE #4536: Script takes ~13x longer to start when comparing development version of stack with 1.9.3
### Steps to reproduce

Contents of `~/tmp/hmm.hs`:

```haskell
#!/usr/bin/env stack
-- stack --resolver lts-13.0 script

main :: IO ()
main = putStrLn "hmm
```

Development version of stack:

```
mgsloan@treetop:~/tmp$ $(which stack) --version
Version 1.10.0, Git revision 570172b8ca0d5fd4a382abadb2951493616b0387 (6826 commits) x86_64 hpack-0.31.1
mgsloan@treetop:~/tmp$ time ./hmm.hs
hmm

real    0m3.513s
user    0m3.299s
sys     0m0.251s
```

I also had to wait quite a while for it to parse ~100,000 cabal files (but that is not included in this particular run)

Stack-1.9.3:

```
mgsloan@treetop:~/tmp$ $(which stack) --version                                                               
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1       
mgsloan@treetop:~/tmp$ time ./hmm.hs                                                                          
hmm                                                                                                           
                                                                                                              
real    0m0.281s
user    0m0.260s
sys     0m0.047s
```

### PR DESCRIPTION
**Pull request by qrilka**
Note: Documentation fixes for https://docs.haskellstack.org/en/stable/ should target the "stable" branch, not master.

Please include the following checklist in your PR:

* [ ] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [ ] The documentation has been updated, if necessary.

Fixes #4536 
Fixes #4624 

I've switched to a script with some imports actually (otherwise there's an easy way to cheat by not getting any packages at all) :
```
#!/usr/bin/env stack
-- stack --resolver lts-13.0 script -v

import System.ByteOrder
import Control.Lens

main :: IO ()
main = putStrLn $ "hmm"
                  ++ ", byte order " ++ show byteOrder
```

And on my local machine I get the following results:
```
qrilka@qdesktop ~/ws/h/stack $ time stack-master script --resolver lts-13.0 hmm.hs
Using resolver: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/13/0.yaml specified on command line
hmm, byte order LittleEndian

real	0m4,874s
user	0m4,748s
sys	0m0,196s
qrilka@qdesktop ~/ws/h/stack $ time stack-master script --resolver lts-13.0 hmm.hs
Using resolver: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/13/0.yaml specified on command line
hmm, byte order LittleEndian

real	0m4,860s
user	0m4,631s
sys	0m0,300s
qrilka@qdesktop ~/ws/h/stack $ time stack script --resolver lts-13.0 hmm.hs
Using resolver: lts-13.0 specified on command line
hmm, byte order LittleEndian

real	0m0,586s
user	0m0,537s
sys	0m0,085s
qrilka@qdesktop ~/ws/h/stack $ time stack script --resolver lts-13.0 hmm.hs
Using resolver: lts-13.0 specified on command line
hmm, byte order LittleEndian

real	0m0,589s
user	0m0,550s
sys	0m0,075s
qrilka@qdesktop ~/ws/h/stack $ time stack-head script --resolver lts-13.0 hmm.hs
Using resolver: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/13/0.yaml specified on command line
Populating module name cache
hmm, byte order LittleEndian

real	0m5,918s
user	0m5,763s
sys	0m0,190s
qrilka@qdesktop ~/ws/h/stack $ time stack-head script --resolver lts-13.0 hmm.hs
Using resolver: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/13/0.yaml specified on command line
hmm, byte order LittleEndian

real	0m0,792s
user	0m0,706s
sys	0m0,134s
qrilka@qdesktop ~/ws/h/stack $ time stack-head script --resolver lts-13.0 hmm.hs
Using resolver: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/13/0.yaml specified on command line
hmm, byte order LittleEndian

real	0m0,759s
user	0m0,646s
sys	0m0,156s
```

Thus we get only noticeable slowdown only when there's no module cache and otherwise `stack script` in this PR is only marginally slower than with the stable Stack. And with #4550 resolved we could get closer to the stable version or even get faster than it.

### CODE REVIEW

File: subs/pantry/src/Pantry/Storage.hs [hunk 1]
```diff
@@ -1023,3 +1043,61 @@ countHackageCabals = do
...
+      moduleName <- getModuleNameId m
+      insert_ PackageExposedModule
+        { packageExposedModuleSnapshotCache = cache
+        , packageExposedModulePackage = package
+        , packageExposedModuleModule = moduleName
+        }
+
+loadExposedModulePackages
+  :: (HasPantryConfig env, HasLogFunc env)
+  => SnapshotCacheHash
```
Comment (snoyberg) [inline subs/pantry/src/Pantry/Storage.hs]: A guess would be that it would be more efficient to use `SnapshotCacheId` here to avoid serializing a `ByteString` each time.

File: subs/pantry/src/Pantry.hs [hunk 2]
```diff
@@ -1501,3 +1505,36 @@ prunePackageWithDeps pkgs getName getDeps (pname, a)  = do
       else do
         modify' $ first (Map.insert pname prunedDeps)
       return $ not (null prunedDeps)
+
```
Comment (snoyberg) [inline subs/pantry/src/Pantry.hs]: Possible alternative API for the three functions below:

```haskell
withSnapshotCache
  :: (HasPantryConfig env, HasLogFunc env)
  => SnapshotCacheHash
  -> RIO env (Map PackageName (Set ModuleName))
  -> ((ModuleName -> RIO env [PackageName]) -> RIO env a)
  -> RIO env a
```

Reasoning: you can provide this function an action which will generate the full snapshot cache in memory on demand. This function can be responsible for checking if the cache already exists and, if not, creating it. This function can also create a single SQLite connection and reuse it for the entire body, bypassing the need to restart a database transaction. Finally, it can internally use the `SnapshotCacheId` without leaking that information to the caller, possibly providing more efficiency.

Comment (qrilka) [reply subs/pantry/src/Pantry.hs]: Yeah, I had somewhat similar idea while working on this but I didn't pursue it further somehow. Will do it now, thanks.

Comment (qrilka) [reply subs/pantry/src/Pantry.hs]: Done in 4d82cddeb0a69d14ab16f26d7c023a8872f4c073 with one exception - SQLite connection is not shared, the main reason is that code reading cabal files also goes into Pantry and requests its own DB connection

File: src/Stack/Script.hs [hunk 3]
```diff
@@ -152,31 +158,110 @@ scriptCmd opts go' = do
...
+        then return pns
+        else Set.union pns <$> getPackagesFromModuleNames mns
+
+getPackagesFromModuleNames
+  :: Set ModuleName
+  -> RIO EnvConfig (Set PackageName)
+getPackagesFromModuleNames mns = do
+    hash <- hashSnapshot
+    withSnapshotCache hash mapSnapshotPackageModules $ \getModulePackages -> do
+        mutableMapping <- mapMutablePackageModules
```
Comment (snoyberg) [inline src/Stack/Script.hs]: The `script` command does not allow for any mutable packages, so if desired for simplicity, I think you could simply add an assertion that there are no mutable packages.

File: src/Stack/Script.hs [hunk 4]
```diff
@@ -152,31 +158,110 @@ scriptCmd opts go' = do
...
+        return $ Set.unions pns `Set.difference` blacklist
+
+hashSnapshot :: RIO EnvConfig SnapshotCacheHash
+hashSnapshot = do
+    sourceMap <- view $ envConfigL . to envConfigSourceMap
+    let wc = whichCompiler $ smCompiler sourceMap
+    compilerInfo <- getCompilerInfo wc
+    let maybePliHash dep | PLImmutable pli <- dpLocation dep =
+                             Just $ immutableLocShaBs pli
+                         | otherwise = Nothing
```
Comment (snoyberg) [inline src/Stack/Script.hs]: Similarly this could be an ``error "No mutable packages are allowed in the `script` command``

File: src/Stack/Script.hs [hunk 5]
```diff
@@ -152,31 +158,110 @@ scriptCmd opts go' = do
...
+      case dpLocation dep of
+          PLImmutable _ -> pure []
+          PLMutable _ -> do
+              gpd <- liftIO $ cpGPD (dpCommon dep)
+              modules <- allExposedModules gpd
+              return [ (m, Set.singleton pname) | m <- modules ]
+
+allExposedModules :: PD.GenericPackageDescription -> RIO EnvConfig [ModuleName]
+allExposedModules gpd = do
+  -- FIXME add os, arch conditionals
```
Comment (snoyberg) [inline src/Stack/Script.hs]: Can you clarify this `FIXME`? It looks like you've already implemented these conditionals correctly.

File: src/Stack/Build/Source.hs [hunk 6]
```diff
@@ -171,13 +166,9 @@ depPackageHashableContent DepPackage {..} = do
...
                 flags = map flagToBs $ Map.toList (cpFlags dpCommon)
-                locationTreeKey (PLIHackage _ _ tk) = tk
-                locationTreeKey (PLIArchive _ pm) = pmTreeKey pm
-                locationTreeKey (PLIRepo _ pm) = pmTreeKey pm
-                treeKeyToBs (TreeKey (BlobKey sha _)) = SHA256.toHexBytes sha
                 ghcOptions = map encodeUtf8 (cpGhcOptions dpCommon)
                 haddocks = if cpHaddocks dpCommon then "haddocks" else ""
-                hash = treeKeyToBs $ locationTreeKey pli
+                hash = immutableLocShaBs pli
             return $ B.concat ([hash, haddocks] ++ flags ++ ghcOptions)
```
Comment (snoyberg) [inline src/Stack/Build/Source.hs]: Possible optimization: instead of using `ByteString`s here, use `Builder`s, which will more efficiently concatenate together. May not be worth the overhead of changing things.

File: src/Stack/Script.hs (hunk 5 above)
Comment (qrilka) [reply src/Stack/Script.hs]: oops

File: src/Stack/Script.hs (hunk 3 above)
Comment (qrilka) [reply src/Stack/Script.hs]: I didn't know about that, is it documented somewhere?

Comment (snoyberg) [reply src/Stack/Script.hs]: I don't think so, it's an implication of the requirement that there's no local config for `stack script`, and when I wrote that documentation, we didn't have the mutable/immutable breakdown yet.

**Comment by qrilka** [comment]
@snoyberg I think I've addressed all the points you raised
